06-wrappers done
js-tasks-ru/vue-20220809_vyacheslav-shatrov pull request #5
Opened 2022-09-17 10:32 UTC by slav73

2022-09-17 10:32 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-09-17 18:14 UTC, ShGKme requested changes
Всё отлично, но в `06-wrappers/06-UiInputDate` требуется решение, не требующее изменения оборачиваемого компонента.

2022-09-17 18:14 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInput.vue
>      },
Создание обёртки над `UiInput` не должно требовать переименования параметра `UiInput`. При таком переименовании больше нельзя использовать на компоненте `v-model` с необходимостью работать через `v-model:value`. Кроме того, имя параметра ничего не меняет в использовании компонента.

Тем более

2022-09-17 18:14 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +  </ui-input>
Значение `dateValue` можно также передавать и со старым именем, через `:model-value="dateValue"`

2022-09-22 18:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-23 12:24 UTC, ShGKme reviewed
Обновления приняты, но добавлены новые задачи

2022-09-25 21:33 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-09-29 22:05 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-09-29 22:05 UTC, ShGKme commented on 07-forms/01-CounterButtonComplete/App.vue
>      <p><counter-button /> - независимый счётчик</p>
Аргумент `:count` нужен, чтобы модель работала именно на параметр `count`.

2022-09-29 22:07 UTC, merged